---
title: "obtencao das paissagens"
author: "CeMECA"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(biomastats)
library(mapview)
library(raster)
```

# Paisagem 1

Considere como coordenadas centrais e posição do campus Lagoa do Sino

-23.59925658469992, -48.52960764232763

```{r}
make_polygon(lat = -23.5992, lon = -48.5296, size = 30, shape = "square")
mapas <- load_rasters(start = 2018, end = 2020, method = "download", export_folder_path = "./mapas-uso-ocupacao")
#save(mapas, file = "mapas.Rdata")
```


```{r}
load("./pre-processamento/mapas30km.Rdata")
```


```{r}
# Para salvar como GeoTIFF
#writeRaster(
#  mapas$raster[[3]], 
#  filename = "./raster.tif",  # nome do arquivo de saída
#  format = "GTiff",             # formato GeoTIFF
#  overwrite = TRUE             # sobrescrever se já existir
#)
```

```{r}
png("mapa_lulc.png", width = 4000, height = 3000, res = 600)
land_vis(mapas_30km, year = 2020)
dev.off()
```
```{r}
results <- get_area(mapas_30km)
library(dplyr)
summa <- results$aggregate_data %>% filter(year == 2020)
summa$area_perc <- 100*summa$area/sum(summa$area)
summa %>% arrange(desc(area_perc))
```


```{r}
land_dist(results, year = 2020)
```

## metrics for forest formation 

```{r}
metrics_forest <- biomastats_metrics(mapas_30km, start = 2018, end = 2020, zone = "23", hemisphere = "south")
```


```{r}
metrics_forest$metrics_table[3,]
```

```{r}
reclass_map(metrics_forest, year = 2020)
```

## metrics for forest formation + plantation

```{r}
metrics_forest <- biomastats_metrics(mapas_30km, start = 2018, end = 2020, zone = "23", hemisphere = "south")
```


```{r}
metrics_forest$metrics_table[3,]
```

```{r}
reclass_map(metrics_forest, year = 2020)
```


